### Endpoint de teste
GET http://localhost:3003/ping


### Exercício 1 - Signup
POST http://localhost:3003/signup
Content-Type: application/json

{

    "nickname": "Sophie",
    "email": "sophia@gmail.com",
    "password": "sophia"

}

### Exercício 2 - Login
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "sophia@gmail.com",
    "password": "sophia"
}

### Exercício 3 - AllUsers
GET http://localhost:3003/users?q=Sophie
Authorization: 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3NTA5MjhjLTZiZTgtNDU4OS1hYTBkLTIwNDZhZmUwODcxNiIsImlhdCI6MTY1OTQ0NzE1NiwiZXhwIjoxNjU5NTMzNTU2fQ.-_5iObztSbuzbRfOkhnQEO8_ccVAvKFaRINjvaktOXM


### Exercício 4 - Endpoint protegido de edição de dados do próprio usuário
PUT http://localhost:3003/users
Authorization: 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ3NTA5MjhjLTZiZTgtNDU4OS1hYTBkLTIwNDZhZmUwODcxNiIsImlhdCI6MTY1OTQ0NzE1NiwiZXhwIjoxNjU5NTMzNTU2fQ.-_5iObztSbuzbRfOkhnQEO8_ccVAvKFaRINjvaktOXM
Content-Type: application/json

    {
        "nickname": "Steph",
        "email": "stephanie@gmail.com",
        "password": "stephanie"
    }

