### Endpoint 0 - Ping (Teste)
GET http://localhost:3003/ping

### Endpoint 1 - Signup (Cadastro de usuário)
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "nickname": "Sophie",
    "email": "sophia@gmail.com",
    "password": "sophia"
}

### Endpoint 2 - Login (Login de usuário)
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "sophia@gmail.com",
    "password": "sophia"
}

### Endpoint 3 - Create Recipe (Cadastro de receita)
POST http://localhost:3003/recipes
Authorization: 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyZjQ3YmY5LWU1OTItNDAwOS04ZTE2LTg4NDUyZDdmNjg0YSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk3MzkwOTYsImV4cCI6MTY1OTgyNTQ5Nn0.bLL2RMIkGCG5LvwNaMvnEdmKPohIyB4PhEpvv4buIWg
Content-Type: application/json

{
    "title": "Pipoca",
    "description": "Pipoca com manteiga de cinema"    
}

### Endpoint 4 - Edit Recipe (Edição de receita)
PUT http://localhost:3003/recipes/103
Authorization: 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyZjQ3YmY5LWU1OTItNDAwOS04ZTE2LTg4NDUyZDdmNjg0YSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk3MzkwOTYsImV4cCI6MTY1OTgyNTQ5Nn0.bLL2RMIkGCG5LvwNaMvnEdmKPohIyB4PhEpvv4buIWg
Content-Type: application/json


{
    "title": "Pipoca doce",
    "description": "Pipoca doce sabor chocolate"
}

### - Endpoint 5 - Delete Recipe (Exclusão de Receita)
DELETE http://localhost:3003/recipes/101
Authorization:.
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyZjQ3YmY5LWU1OTItNDAwOS04ZTE2LTg4NDUyZDdmNjg0YSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk3MzkwMTMsImV4cCI6MTY1OTgyNTQxM30.UdqoHOn4YzIvXHQkVe8ACxItywFZ340mGdvgSVAVBAs
Content-Type: application/json

### - Endpoint 6 - Search Recipes (Busca de Receita)
GET http://localhost:3003/recipes?search=brigadeiro
Authorization: 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyZjQ3YmY5LWU1OTItNDAwOS04ZTE2LTg4NDUyZDdmNjg0YSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk3MzkwOTYsImV4cCI6MTY1OTgyNTQ5Nn0.bLL2RMIkGCG5LvwNaMvnEdmKPohIyB4PhEpvv4buIWg
Content-Type: application/json

### Endpoint 7 - Delete User (Exclusão de Usuário)
DELETE http://localhost:3003/users/3
Authorization: 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAyZjQ3YmY5LWU1OTItNDAwOS04ZTE2LTg4NDUyZDdmNjg0YSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NTk3MzkwMTMsImV4cCI6MTY1OTgyNTQxM30.UdqoHOn4YzIvXHQkVe8ACxItywFZ340mGdvgSVAVBAs
